bookmarks/account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework.routers import SimpleRouter

from . import views
from .views import ChangePasswordView, SendMailView, UserViewSet, DashboardView, UserFollowView


router = SimpleRouter()
router.register(r'api', UserViewSet, basename='api')


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/log-out.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('', include('django.contrib.auth.urls')),

    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),

    # api
    path('api/auth/', views.AuthAPIView.as_view(), name='api_auth'),
    path('api/register/', views.RegisterAPIView.as_view(), name='api_register'),

    path('api/change-password/', ChangePasswordView.as_view()),
    path('api/send/', SendMailView.as_view()),
    path('api/dashboard/', DashboardView.as_view()),
    path('api/users/follow/', UserFollowView.as_view()),
]
urlpatterns += router.urls

bookmarks/bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('sub/', include('sub.urls', namespace='sub')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from . import views
from .views import ImageViewSet, ImageCreateView, ImageRankingView, ImageLikeView

app_name = 'images'

router = SimpleRouter()

router.register(r'api', ImageViewSet, basename='api')

urlpatterns = [
    path('api/ranking/', ImageRankingView.as_view()),
    path('api/create-image/', ImageCreateView.as_view()),
    path('api/like/', ImageLikeView.as_view()),

    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('ranking/', views.image_ranking, name='ranking'),
    path('', views.image_list, name='list'),
]

urlpatterns += router.urls

bookmarks/sub/urls.py
from django.urls import path

from .views import CheckoutSession, CheckoutSessionSuccess, CheckoutSessionCanceled, CustomerPortal, web_hooks, \
    CheckoutSessionView, CustomerPortalView

app_name = 'sub'

urlpatterns = [
    path('create-checkout-session/', CheckoutSession.as_view(), name='create-checkout-session'),
    path('success/', CheckoutSessionSuccess.as_view(), name='success'),
    path('canceled/', CheckoutSessionCanceled.as_view(), name='cancel'),
    path('create-customer-portal-session/', CustomerPortal.as_view(), name='create-customer-portal-session'),
    path('webhooks/', web_hooks, name='webhooks'),

    path('api/create-checkout-session/', CheckoutSessionView.as_view()),
    path('api/create-customer-portal-session/', CustomerPortalView.as_view()),
]

bookmarks/account/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)


class Contact(models.Model):
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)


# Add following field to User dynamically
User.add_to_class('following', models.ManyToManyField('self',
                                                      through=Contact,
                                                      related_name='followers',
                                                      symmetrical=False))

User.add_to_class('stripe_id', models.CharField(max_length=200, blank=True, null=True))
User.add_to_class('stripe_subscription_status', models.CharField(max_length=30, blank=True, null=True))

bookmarks/account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

bookmarks/account/views.py
from decouple import config
from django.core.mail import send_mass_mail
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from rest_framework.filters import OrderingFilter
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.viewsets import ModelViewSet
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

from common.decorators import ajax_required
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile, Contact

from django.contrib import messages
from actions.utils import create_action
from actions.models import Action

from rest_framework import generics, permissions, status
from .api.serializers import RegisterSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework_jwt.settings import api_settings

from .serializers import ChangePasswordSerializer, SendMailSerializer, UserSerializer, ActionSerializer, \
    UserFollowSerializer
from .tasks import send_mail_task

jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER
jwt_response_payload_handler = api_settings.JWT_RESPONSE_PAYLOAD_HANDLER


class UserViewSet(ModelViewSet):
    queryset = User.objects.filter(is_active=True)
    serializer_class = UserSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = ['username', 'is_superuser']
    ordering = ['id']
    permission_classes = [IsAuthenticated]


class DashboardView(APIView):
    """ An endpoint for actions.
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        actions = Action.objects.exclude(user=request.user)
        following_ids = request.user.following.values_list('id', flat=True)
        if following_ids:
            # If the current user has subscribed to somebody,
            # only actions of these users will be displayed.
            actions = actions.filter(user_id__in=following_ids)[:10]
        serializer = ActionSerializer(actions, many=True)
        return Response(serializer.data)


class UserFollowView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        serializer = UserFollowSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            user_from = serializer.validated_data['user']
            user_to_id = serializer.validated_data['id']
            action = serializer.validated_data['action']
            if user_to_id and action:
                try:
                    user_to = User.objects.get(id=user_to_id)
                    if action == 'follow':
                        Contact.objects.get_or_create(user_from=user_from, user_to=user_to)
                        create_action(user_from, 'is following', user_to)
                    else:
                        Contact.objects.filter(user_from=user_from, user_to=user_to).delete()
                    return Response(serializer.data, status=status.HTTP_201_CREATED)
                except User.DoesNotExist:
                    return Response(status=status.HTTP_404_NOT_FOUND)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class ChangePasswordView(generics.UpdateAPIView):
    """ An endpoint for changing password.
    """
    serializer_class = ChangePasswordSerializer
    model = User
    permission_classes = [IsAuthenticated]
    # authentication_classes = {SessionAuthentication, TokenAuthentication, JSONWebTokenAuthentication}

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def update(self, request, *args, **kwargs):
        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            # Check old password
            if not self.object.check_password(serializer.data.get("old_password")):
                return Response({"old_password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)
            # set_password also hashes the password that the user will get
            self.object.set_password(serializer.data.get("new_password"))
            self.object.save()
            response = {
                'status': 'success',
                'code': status.HTTP_200_OK,
                'message': 'Password updated successfully',
                'data': []
            }
            return Response(response)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class SendMailView(APIView):
    """ View for sending mail to all users
    """
    permission_classes = [IsAuthenticated]

    def post(self, request):
        email_list = list(User.objects.all().values_list('email', flat=True))

        serializer = SendMailSerializer(data=request.data)
        if serializer.is_valid():
            subject = serializer.validated_data["subject"]
            text = serializer.validated_data["text"]
            sender = config('EMAIL_HOST_USER')
            message = (subject, text, sender, email_list)
            send_mail_task.delay((message,), fail_silently=False)
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.data)


@login_required
def dashboard(request):
    # Display of all actions by default
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    if following_ids:
        # If the current user has subscribed to somebody,
        # only actions of these users will be displayed.
        actions = actions.filter(user_id__in=following_ids)
    actions = actions.select_related('user', 'user__profile').prefetch_related('target')[:10]
    return render(request, 'account/dashboard.html', {'section': 'dashboard', 'actions': actions})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # Create the user profile
            Profile.objects.create(user=new_user)
            create_action(new_user, 'has created an account')
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'account/user/list.html', {'section': 'people', 'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'account/user/detail.html', {'section': 'people', 'user': user})


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'ok'})


# API
class RegisterAPIView(generics.CreateAPIView):
    queryset = User.objects.all()
    permission_classes = [permissions.AllowAny,]
    serializer_class = RegisterSerializer


class AuthAPIView(APIView):
    permission_classes = [permissions.AllowAny]

    def post(self, request, *args, **kwargs):
        data = request.data
        user = User.objects.filter(Q(username__iexact=data['username']) | Q(email__iexact=data['username']))
        if user.exists():
            user = user.first()
            if user.check_password(data['password']):
                if user.is_active:
                    payload     = jwt_payload_handler(user)
                    token       = jwt_encode_handler(payload)
                    response    = jwt_response_payload_handler(token, user, request)
                    return Response(response)
                return Response({'detail': 'Your account has been disabled'}, status=400)
            return Response({'detail': 'Invalid username or password'}, status=400)

bookmarks/account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link href="{% static 'css/base.css' %}" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

	<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>

	{% block extra_head %}
	{% endblock %}

</head>

<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-success">
		<div class="container-fluid">
			<a class="navbar-brand col-md-2" href="#">Bookmarks</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
					data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
					aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
				{% if user.is_authenticated %}
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">My dashboard</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'images:list' %}">Images</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'user_list' %}">People</a>
					</li>
				</ul>
				{% endif %}

				<div class="nav justify-content-end">
					{% if user.is_authenticated %}
						<span class="navbar-text">Hello, {{ user.username }} ::::: stripe_id ::::: {{ user.stripe_id }}</span>
						<a class="btn text-light" href="{% url 'logout' %}">Logout</a>
					{% else %}
						<span class="navbar-text">You are not logged in</span>
						<a class="btn text-light" href="{% url 'login' %}">Login</a>
					{% endif %}
				</div>
				<!-- Subscribe -->
				<button class="btn btn-info" id="checkout-button">Subscribe</button>
				<!-- Manage billing -->
				<form method="POST" action="/sub/create-customer-portal-session/">
					{% csrf_token %}
					<button type="submit" class="btn btn-info">Manage billing</button>
    			</form>

			</div>
		</div>
	</nav>

	{% if messages %}
		<ul class="messages">
		{% for message in messages %}
			<li class="{{ message.tags }}">
				{{ message|safe }}
				<a href="#" class="close">x</a>
			</li>
		{% endfor %}
		</ul>
	{% endif %}

	<div class="container-fluid mt-5">
		{% block content %}{% endblock %}
	</div>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
	<script>
		var csrftoken = Cookies.get('csrftoken');
		function csrfSafeMethod(method) {
		  // these HTTP methods do not require CSRF protection
		  return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}
		$.ajaxSetup({
		  beforeSend: function(xhr, settings) {
			if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
			  xhr.setRequestHeader("X-CSRFToken", csrftoken);
			}
		  }
		});
		$(document).ready(function(){
		  {% block domready %}
		  {% endblock %}
		   });
	</script>

	<script type="text/javascript">
		// Create an instance of the Stripe object with your publishable API key
		var stripe = Stripe("pk_test_51IXqAwIBBCpvms2A0tZdmSSd78uaVKdZ86iOhZrbKAxO4uf41sgvHWyp6q71h11shWh0ZNFR1BLZBnzmgzSKWd8a00T1RT6ZMQ");
		var checkoutButton = document.getElementById("checkout-button");
		checkoutButton.addEventListener("click", function () {
		  fetch("{% url 'sub:create-checkout-session' %}", {
			method: "POST",
			headers: {
				'X-CSRFToken': csrftoken,
			}
		  })
			.then(function (response) {
			  return response.json();
			})
			.then(function (session) {
			  return stripe.redirectToCheckout({ sessionId: session.id });res.json
			})
			.then(function (result) {
			  // If redirectToCheckout fails due to a browser or network
			  // error, you should display the localized error message to your
			  // customer using error.message.
			  if (result.error) {
				alert(result.error.message);
			  }
			})
			.catch(function (error) {
			  console.error("Error:", error);
			});
		});
	</script>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>

	{% block extra_js %}
	{% endblock %}

</body>
</html>